# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_providers.azure.ipynb.

# %% auto #0
__all__ = ['AzureProvider']

# %% ../../nbs/01_providers.azure.ipynb #182df542
import os
from openai import AzureOpenAI

class AzureProvider:
    "OpenAI chat completions via an Azure deployment."
    def __init__(self,
                 deployment: str = "gpt-5.4",
                 endpoint: str = "https://pablo-ml1b1csr-eastus2.cognitiveservices.azure.com",
                 api_version: str = "2024-12-01-preview",
                 api_key_env: str = "AZURE_API_KEY",
                 max_completion_tokens: int = 16384):
        self.deployment, self.endpoint = deployment, endpoint
        self.api_version, self.api_key_env = api_version, api_key_env
        self.max_completion_tokens = max_completion_tokens
        self._client = None

    def _get_client(self):
        if self._client is None:
            self._client = AzureOpenAI(api_key=os.environ[self.api_key_env],
                                       azure_endpoint=self.endpoint,
                                       api_version=self.api_version)
        return self._client

    def complete(self, messages: list[dict]) -> str:
        resp = self._get_client().chat.completions.create(
            model=self.deployment, messages=messages,
            max_completion_tokens=self.max_completion_tokens,
        )
        return resp.choices[0].message.content
