# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_providers.openai.ipynb.

# %% auto #0
__all__ = ['OpenAIProvider']

# %% ../../nbs/01_providers.openai.ipynb #182df542
import json, os
from openai import AzureOpenAI
from ..core import Tool, Turn, ToolCall

class OpenAIProvider:
    "OpenAI Chat Completions over the `openai` SDK. `complete()` is one round-trip — driven by `run_completion` when tools are involved."
    def __init__(self,
                 deployment: str | None = None,
                 endpoint: str | None = None,
                 api_version: str = "2024-12-01-preview",
                 api_key_env: str = "AZURE_API_KEY",
                 max_completion_tokens: int = 16384):
        self.deployment = deployment or os.environ.get("AZURE_OPENAI_DEPLOYMENT")
        self.endpoint = endpoint or os.environ.get("AZURE_OPENAI_ENDPOINT")
        self.api_version, self.api_key_env = api_version, api_key_env
        self.max_completion_tokens = max_completion_tokens
        self._client = None

    def _get_client(self):
        if self._client is None:
            if not self.endpoint:
                raise RuntimeError("OpenAIProvider: no endpoint. Set $AZURE_OPENAI_ENDPOINT or pass endpoint=...")
            if not self.deployment:
                raise RuntimeError("OpenAIProvider: no deployment. Set $AZURE_OPENAI_DEPLOYMENT or pass deployment=...")
            self._client = AzureOpenAI(api_key=os.environ[self.api_key_env],
                                       azure_endpoint=self.endpoint,
                                       api_version=self.api_version)
        return self._client

    def complete(self, messages: list[dict], tools: list[Tool] = None) -> Turn:
        schemas = [t.schema for t in (tools or [])]
        kw = {"tools": schemas} if schemas else {}
        resp = self._get_client().chat.completions.create(
            model=self.deployment, messages=messages,
            max_completion_tokens=self.max_completion_tokens, **kw)
        choice = resp.choices[0]
        m = choice.message
        tcs = [ToolCall(id=tc.id, name=tc.function.name,
                        args=json.loads(tc.function.arguments))
               for tc in (m.tool_calls or [])]
        return Turn(text=m.content, tool_calls=tcs,
                    usage=resp.usage.model_dump() if resp.usage else None,
                    finish_reason=choice.finish_reason)
