"""Fetch a URL and extract its readable content as markdown, so the model can decide *after* seeing search snippets that it wants to read the full page."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_tools.browse.ipynb.

# %% auto #0
__all__ = ['browse']

# %% ../../nbs/03_tools.browse.ipynb #5ee7b234
import trafilatura
from ..core import Tool

def _browse(url: str, max_chars: int = 10000) -> str:
    "Fetch `url` and return its main readable content as markdown, truncated to `max_chars`."
    html = trafilatura.fetch_url(url)
    if not html: return f"(fetch failed for {url})"
    extracted = trafilatura.extract(html, output_format="markdown",
                                    include_links=True, include_tables=True)
    if not extracted: return f"(no readable content extracted from {url})"
    if len(extracted) > max_chars:
        return extracted[:max_chars] + f"\n\n…(truncated; original {len(extracted)} chars — call again with a higher `max_chars` to read more)"
    return extracted

# %% ../../nbs/03_tools.browse.ipynb #browse-tool
browse = Tool(
    schema={
        "type": "function",
        "function": {
            "name": "browse",
            "description": "Fetch a single URL and return its main readable content as markdown. Use this after `web_search` when a result looks promising and you need the full page text, not just the snippet.",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The URL to fetch, including scheme (https://...)."},
                    "max_chars": {"type": "integer", "description": "Cap on returned characters (default 10000). Raise this if you got a truncation marker and want to read more.", "default": 10000},
                },
                "required": ["url"],
            },
        },
    },
    fn=_browse,
)
