"""Web search as a tool the model can call, backed by the Brave Search API."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_tools.search.ipynb.

# %% auto #0
__all__ = ['BRAVE_SEARCH_URL', 'web_search']

# %% ../../nbs/02_tools.search.ipynb #9d6e7f10
import os
import httpx
from ..core import Tool

BRAVE_SEARCH_URL = "https://api.search.brave.com/res/v1/web/search"

def _brave_search(query: str, k: int = 5, api_key_env: str = "BRAVE_API_KEY") -> str:
    "Call the Brave Search API and return a compact markdown digest of the top `k` web results."
    r = httpx.get(
        BRAVE_SEARCH_URL,
        params={"q": query, "count": k},
        headers={"X-Subscription-Token": os.environ[api_key_env],
                 "Accept": "application/json"},
        timeout=20.0,
    )
    r.raise_for_status()
    results = (r.json().get("web") or {}).get("results", [])[:k]
    if not results: return "(no results)"
    return "\n\n".join(
        f"## {x.get('title','').strip()}\n{x.get('url','')}\n{x.get('description','').strip()}"
        for x in results
    )

web_search = Tool(
    schema={
        "type": "function",
        "function": {
            "name": "web_search",
            "description": "Search the public web via the Brave Search API. Returns a short markdown digest of the top results (title, URL, snippet) so the model can decide which to follow up on.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query."},
                    "k": {"type": "integer", "description": "How many results to return (default 5, max 20).", "default": 5},
                },
                "required": ["query"],
            },
        },
    },
    fn=_brave_search,
)
