# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdialog',
                'doc_host': 'https://slashpablo.github.io',
                'git_url': 'https://github.com/slashpablo/nbdialog',
                'lib_path': 'nbdialog'},
  'syms': { 'nbdialog.core': { 'nbdialog.core._current_notebook': ('core.html#_current_notebook', 'nbdialog/core.py'),
                             'nbdialog.core._get_client': ('core.html#_get_client', 'nbdialog/core.py'),
                             'nbdialog.core._is_prompt': ('core.html#_is_prompt', 'nbdialog/core.py'),
                             'nbdialog.core._join': ('core.html#_join', 'nbdialog/core.py'),
                             'nbdialog.core._output_text': ('core.html#_output_text', 'nbdialog/core.py'),
                             'nbdialog.core._parse_prompt_args': ('core.html#_parse_prompt_args', 'nbdialog/core.py'),
                             'nbdialog.core._response_markdown': ('core.html#_response_markdown', 'nbdialog/core.py'),
                             'nbdialog.core._strip_magic': ('core.html#_strip_magic', 'nbdialog/core.py'),
                             'nbdialog.core.notebook_to_messages': ('core.html#notebook_to_messages', 'nbdialog/core.py'),
                             'nbdialog.core.prompt': ('core.html#prompt', 'nbdialog/core.py')}}}
