"""Minimal IPython notebook integration for an LLM `%%prompt` cell magic. Inspired by fast.ai's solveit."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['system_prompt', 'AZURE_OPENAI_DEPLOYMENT', 'AZURE_OPENAI_ENDPOINT', 'AZURE_OPENAI_API_VERSION',
           'notebook_to_messages', 'prompt']

# %% ../nbs/00_core.ipynb #a456f188
from IPython.display import Markdown, display
from IPython.core.magic import register_cell_magic

from openai import AzureOpenAI

from pathlib import Path
import argparse, json, os, shlex

# %% ../nbs/00_core.ipynb #74c72bd5
system_prompt = """You are an AI assistant embedded inside an IPython notebook through a `%%prompt` cell magic. The notebook is a linear sequence of markdown, code, and prompt cells executed in a single persistent kernel — state from code cells carries forward. When the user runs a prompt cell, every cell above it (sources and captured outputs) is sent to you as the conversation history; previous prompt cells appear as your prior assistant turns. The dialog *is* the notebook.

Be concise, direct, and incremental. Match response length to the question. Do not pad, restate, or end with "let me know if...". Use fenced code blocks with language tags. Default to idiomatic Python — comprehensions, broadcasting, fastcore-style brevity. Short single-line docstrings; no inline comments unless a constraint is genuinely non-obvious.

Your knowledge cutoff is January 2026."""

# %% ../nbs/00_core.ipynb #cd1ec005
def _current_notebook(cell_id=None):
    "Resolve the path of the notebook this kernel is serving."
    name = os.environ.get("JPY_SESSION_NAME")
    if name and Path(name).exists(): return Path(name)
    raise RuntimeError("Cannot determine current notebook; save the file or set JPY_SESSION_NAME")

# %% ../nbs/00_core.ipynb #a030be43
def _join(x): return "".join(x) if isinstance(x, list) else x

# %% ../nbs/00_core.ipynb #13d16bf0
def _is_prompt(cell):
    "True if `cell` is a code cell whose source starts with the %%prompt magic."
    if cell.get("cell_type") != "code": return False
    return _join(cell.get("source", "")).lstrip().startswith("%%prompt")

# %% ../nbs/00_core.ipynb #71a399c1
def _strip_magic(src):
    "Drop the leading %%prompt line from a prompt cell's source."
    return "\n".join(_join(src).splitlines()[1:])

# %% ../nbs/00_core.ipynb #e70e627c
def _output_text(out):
    "Extract a readable string from one nbformat output entry (for context, not response)."
    if out.get("output_type") == "stream": return _join(out.get("text", []))
    data = out.get("data", {})
    if "text/markdown" in data: return _join(data["text/markdown"])
    if "text/plain"    in data: return _join(data["text/plain"])
    return ""

def _response_markdown(cell):
    "Return the model's rendered markdown response stored in this cell's outputs, or None."
    for o in cell.get("outputs", []):
        data = o.get("data", {})
        if "text/markdown" in data: return _join(data["text/markdown"])
    return None

# %% ../nbs/00_core.ipynb #b2f647c5
def notebook_to_messages(cells, up_to_id, system=None):
    "Build chat messages from `cells` up to and including the cell with id `up_to_id`."
    msgs = [{"role": "system", "content": system or system_prompt}]
    for c in cells:
        src = _join(c["source"])
        is_current = c.get("id") == up_to_id
        if _is_prompt(c):
            msgs.append({"role": "user", "content": _strip_magic(src)})
            if not is_current:
                resp = _response_markdown(c)
                if resp: msgs.append({"role": "assistant", "content": resp})
        else:
            msgs.append({"role": "user", "content": src})
            for o in c.get("outputs", []):
                txt = _output_text(o)
                if txt: msgs.append({"role": "user", "content": f"# Output:\n{txt}"})
        if is_current: break
    return msgs

# %% ../nbs/00_core.ipynb #2a0766c6
AZURE_OPENAI_DEPLOYMENT = "gpt-5.4"
AZURE_OPENAI_ENDPOINT   = "https://pablo-ml1b1csr-eastus2.cognitiveservices.azure.com"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"

_client = None
def _get_client():
    global _client
    if _client is None:
        _client = AzureOpenAI(
            api_key=os.environ["AZURE_API_KEY"],
            azure_endpoint=AZURE_OPENAI_ENDPOINT,
            api_version=AZURE_OPENAI_API_VERSION,
        )
    return _client

# %% ../nbs/00_core.ipynb #5ac6d750
def _parse_prompt_args(line):
    "Parse the magic line, e.g. `%%prompt -f`."
    p = argparse.ArgumentParser(prog="%%prompt", add_help=False)
    p.add_argument("-f", "--force", action="store_true",
                   help="bypass cache and call the model even if this cell has output")
    return p.parse_args(shlex.split(line or ""))

# %% ../nbs/00_core.ipynb #09148757
@register_cell_magic
def prompt(line, cell):
    "Send the notebook-so-far to the LLM and render its reply as markdown."
    args = _parse_prompt_args(line)
    ip = get_ipython()
    cell_id = ip.parent_header.get("metadata", {}).get("cellId")
    if not cell_id:
        raise RuntimeError("No cellId in parent_header — requires JupyterLab ≥ 3.5")

    nb_path = _current_notebook(cell_id)
    cells = json.loads(nb_path.read_text())["cells"]
    current = next((c for c in cells if c.get("id") == cell_id), None)

    if not args.force and current:
        cached = _response_markdown(current)
        if cached:
            display(Markdown(cached))
            return

    messages = notebook_to_messages(cells, up_to_id=cell_id)
    resp = _get_client().chat.completions.create(
        model=AZURE_OPENAI_DEPLOYMENT,
        messages=messages,
        max_completion_tokens=16384,
    )
    display(Markdown(resp.choices[0].message.content))
