"""Minimal IPython notebook integration for an LLM `%%prompt` cell magic. Inspired by fast.ai's solveit."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['system_prompt', 'notebook_to_messages', 'Provider', 'Tool', 'set_provider', 'get_provider', 'set_tools', 'get_tools',
           'Trace', 'prompt']

# %% ../nbs/00_core.ipynb #a456f188
from IPython.display import Markdown, display
from IPython.core.magic import register_cell_magic

from pathlib import Path
import argparse, json, os, shlex

# %% ../nbs/00_core.ipynb #74c72bd5
system_prompt = """You are an AI assistant embedded inside an IPython notebook through a `%%prompt` cell magic. The notebook is a linear sequence of markdown, code, and prompt cells executed in a single persistent kernel — state from code cells carries forward. When the user runs a prompt cell, every cell above it (sources and captured outputs) is sent to you as the conversation history; previous prompt cells appear as your prior assistant turns. The dialog *is* the notebook.

Be concise, direct, and incremental. Match response length to the question. Do not pad, restate, or end with "let me know if...". Use fenced code blocks with language tags. Default to idiomatic Python — comprehensions, broadcasting, fastcore-style brevity. Short single-line docstrings; no inline comments unless a constraint is genuinely non-obvious.

Your knowledge cutoff is January 2026."""

# %% ../nbs/00_core.ipynb #cd1ec005
def _current_notebook():
    "Resolve the path of the notebook this kernel is serving."
    name = os.environ.get("JPY_SESSION_NAME")
    if name and Path(name).exists(): return Path(name)
    raise RuntimeError("Cannot determine current notebook; save the file or set JPY_SESSION_NAME")

# %% ../nbs/00_core.ipynb #a030be43
def _join(x): return "".join(x) if isinstance(x, list) else x

# %% ../nbs/00_core.ipynb #13d16bf0
def _is_prompt(cell):
    "True if `cell` is a code cell whose source starts with the %%prompt magic."
    if cell.get("cell_type") != "code": return False
    return _join(cell.get("source", "")).lstrip().startswith("%%prompt")

# %% ../nbs/00_core.ipynb #71a399c1
def _strip_magic(src):
    "Drop the leading %%prompt line from a prompt cell's source."
    return "\n".join(_join(src).splitlines()[1:])

# %% ../nbs/00_core.ipynb #e70e627c
def _output_text(out):
    "Extract a readable string from one nbformat output entry (for context, not response)."
    if out.get("output_type") == "stream": return _join(out.get("text", []))
    data = out.get("data", {})
    if "text/markdown" in data: return _join(data["text/markdown"])
    if "text/plain"    in data: return _join(data["text/plain"])
    return ""

def _response_markdown(cell):
    "Return the model's rendered markdown response stored in this cell's outputs, or None."
    for o in cell.get("outputs", []):
        data = o.get("data", {})
        if "text/markdown" in data: return _join(data["text/markdown"])
    return None

# %% ../nbs/00_core.ipynb #b2f647c5
def notebook_to_messages(cells, up_to_id, system=None):
    "Build chat messages from `cells` up to and including the cell with id `up_to_id`."
    msgs = [{"role": "system", "content": system or system_prompt}]
    for c in cells:
        src = _join(c["source"])
        is_current = c.get("id") == up_to_id
        if _is_prompt(c):
            msgs.append({"role": "user", "content": _strip_magic(src)})
            if not is_current:
                resp = _response_markdown(c)
                if resp: msgs.append({"role": "assistant", "content": resp})
        else:
            msgs.append({"role": "user", "content": src})
            for o in c.get("outputs", []):
                txt = _output_text(o)
                if txt: msgs.append({"role": "user", "content": f"# Output:\n{txt}"})
        if is_current: break
    return msgs

# %% ../nbs/00_core.ipynb #8ccf514d
from typing import Protocol, runtime_checkable

@runtime_checkable
class Provider(Protocol):
    "A vendor-agnostic chat-completion contract: messages in, text out, plus optional tools and trace."
    def complete(self, messages: list[dict], tools: list = None, trace: "Trace | None" = None) -> str: ...

# %% ../nbs/00_core.ipynb #e815ac8c
from typing import NamedTuple, Callable

class Tool(NamedTuple):
    "A schema/function pair the model can call. `schema` is an OpenAI-shaped tool envelope."
    schema: dict
    fn: Callable

_provider: "Provider | None" = None
_tools: list[Tool] = []

def set_provider(p: Provider) -> None:
    "Register `p` as the provider the `%%prompt` magic will call."
    global _provider
    _provider = p

def get_provider() -> Provider:
    "Return the active provider, or raise with the fix in the message."
    if _provider is None:
        raise RuntimeError("Call nbdialog.set_provider(AzureProvider()) first.")
    return _provider

def set_tools(tools: list[Tool]) -> None:
    "Register the `Tool`s available on every `%%prompt`."
    global _tools
    _tools = list(tools)

def get_tools() -> list[Tool]:
    "Return the currently registered tools."
    return _tools

# %% ../nbs/00_core.ipynb #trace-code
import html, time

_TRACE_CSS = """<style>
.nbd-trace { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; margin: 0.5em 0; }
.nbd-trace > summary { cursor: pointer; user-select: none; padding: 4px 8px; background: rgba(127,127,127,0.10); border-radius: 4px; }
.nbd-trace .nbd-turn { padding: 6px 10px; border-left: 2px solid rgba(127,127,127,0.3); margin: 6px 0 6px 12px; }
.nbd-trace .nbd-badge { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 10px; font-weight: 600; margin-right: 6px; vertical-align: 1px; }
.nbd-trace .nbd-badge-prompt { background: rgba(127,127,127,0.20); color: inherit; }
.nbd-trace .nbd-badge-model  { background: rgba(64,128,255,0.18);  color: #4080ff; }
.nbd-trace .nbd-badge-tool   { background: rgba(255,165,0,0.20);   color: #d67a00; }
.nbd-trace .nbd-meta { color: rgba(127,127,127,0.85); font-size: 11px; }
.nbd-trace pre { background: rgba(127,127,127,0.08); padding: 6px 8px; border-radius: 3px; white-space: pre-wrap; word-break: break-word; margin: 4px 0; font-size: 11px; }
.nbd-trace details { margin: 4px 0; }
.nbd-trace details > summary { cursor: pointer; user-select: none; }
</style>"""

class Trace:
    "Records the immediate loop (prompt, model turns, tool calls). Renders as a collapsible HTML block."
    def __init__(self):
        self.prompt: str = ""
        self.turns: list[dict] = []
        self._t0 = time.perf_counter()
        self._tokens = 0

    def set_prompt(self, text: str) -> None: self.prompt = text

    def add_model_turn(self, content, tool_calls, usage, dt):
        self.turns.append({"kind": "model", "content": content,
                           "tool_calls": list(tool_calls or []),
                           "usage": usage, "dt": dt})
        if usage: self._tokens += usage.get("total_tokens") or 0

    def add_tool_turn(self, name, args, result, dt):
        self.turns.append({"kind": "tool", "name": name, "args": args,
                           "result": result, "dt": dt})

    @property
    def total_dt(self): return time.perf_counter() - self._t0

    def _repr_html_(self): return _render_trace_html(self)

def _render_trace_html(trace: "Trace") -> str:
    "Render a `Trace` as a collapsible HTML disclosure block."
    e = html.escape
    n_model = sum(1 for t in trace.turns if t["kind"] == "model")
    n_tool  = sum(1 for t in trace.turns if t["kind"] == "tool")
    header_bits = [f"{n_model} model turn" + ("s" if n_model != 1 else ""),
                   f"{n_tool} tool call" + ("s" if n_tool != 1 else ""),
                   f"{trace.total_dt:.1f}s"]
    if trace._tokens: header_bits.append(f"{trace._tokens:,} tokens")
    summary = "trace · " + " · ".join(header_bits)

    parts = [_TRACE_CSS, f'<details class="nbd-trace"><summary>{e(summary)}</summary>']
    if trace.prompt:
        parts.append('<div class="nbd-turn">'
                     '<span class="nbd-badge nbd-badge-prompt">prompt</span>'
                     f'<pre>{e(trace.prompt)}</pre></div>')
    for i, t in enumerate(trace.turns):
        if t["kind"] == "model":
            usage = t.get("usage") or {}
            meta = f'turn {i+1} · {t["dt"]:.2f}s'
            if usage.get("total_tokens"): meta += f' · {usage["total_tokens"]:,} tokens'
            body = []
            for tc in t["tool_calls"]:
                args_json = json.dumps(tc["args"], indent=2, ensure_ascii=False)
                body.append(f'<details><summary>calls <code>{e(tc["name"])}</code></summary>'
                            f'<pre>{e(args_json)}</pre></details>')
            if t["content"]:
                body.append(f'<pre>{e(t["content"])}</pre>')
            if not body: body = ['<span class="nbd-meta">(no content; loop exiting)</span>']
            parts.append('<div class="nbd-turn">'
                         '<span class="nbd-badge nbd-badge-model">model</span>'
                         f'<span class="nbd-meta">{e(meta)}</span>'
                         + "".join(body) + '</div>')
        else:
            args_inline = ", ".join(f'{k}={json.dumps(v, ensure_ascii=False)}'
                                    for k, v in t["args"].items())
            meta = f'{t["name"]}({args_inline}) · {t["dt"]:.2f}s · {len(t["result"]):,} chars'
            parts.append('<div class="nbd-turn">'
                         '<span class="nbd-badge nbd-badge-tool">tool</span>'
                         f'<span class="nbd-meta">{e(meta)}</span>'
                         f'<details><summary>result</summary>'
                         f'<pre>{e(t["result"])}</pre></details></div>')
    parts.append('</details>')
    return "".join(parts)

# %% ../nbs/00_core.ipynb #5ac6d750
def _parse_prompt_args(line):
    "Parse the magic line, e.g. `%%prompt -f --trace`."
    p = argparse.ArgumentParser(prog="%%prompt", add_help=False)
    p.add_argument("-f", "--force", action="store_true",
                   help="bypass cache and call the model even if this cell has output")
    p.add_argument("--trace", action="store_true",
                   help="render the model/tool loop alongside the final answer")
    return p.parse_args(shlex.split(line or ""))

# %% ../nbs/00_core.ipynb #09148757
from IPython.display import HTML

def _cached_trace_html(cell):
    "Return the persisted trace HTML stored in a cell's outputs, or None."
    for o in cell.get("outputs", []):
        h = o.get("data", {}).get("text/html")
        if h:
            s = _join(h)
            if "nbd-trace" in s: return s
    return None

@register_cell_magic
def prompt(line, cell):
    "Send the notebook-so-far to the LLM and render its reply as markdown."
    args = _parse_prompt_args(line)
    ip = get_ipython()
    cell_id = ip.parent_header.get("metadata", {}).get("cellId")
    if not cell_id:
        raise RuntimeError("No cellId in parent_header — requires JupyterLab ≥ 3.5")

    nb_path = _current_notebook()
    cells = json.loads(nb_path.read_text())["cells"]
    current = next((c for c in cells if c.get("id") == cell_id), None)

    if not args.force and current:
        cached = _response_markdown(current)
        if cached:
            if args.trace:
                cached_trace = _cached_trace_html(current)
                if cached_trace: display(HTML(cached_trace))
            display(Markdown(cached))
            return

    trace = Trace() if args.trace else None
    if trace is not None: trace.set_prompt(cell)
    messages = notebook_to_messages(cells, up_to_id=cell_id)
    answer = get_provider().complete(messages, tools=get_tools() or None, trace=trace)
    if trace is not None: display(trace)
    display(Markdown(answer))
